#!/usr/bin/env node
/**
 * Generate the PNG favicon / PWA icon set from `public/favicon.svg`.
 *
 * Run manually after the SVG changes:  node scripts/generate-icons.mjs
 *
 * Outputs:
 *   public/favicon-16x16.png
 *   public/favicon-32x32.png
 *   public/apple-touch-icon.png   (180×180)
 *   public/icon-192.png
 *   public/icon-512.png
 *   public/icon-512-maskable.png  (same artwork; SVG's rounded square keeps
 *                                  the M inside the maskable safe zone)
 *
 * `og-default.png` (1200×630) is generated by a separate Satori-driven
 * pipeline in Sprint 2.
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { Resvg } from "@resvg/resvg-js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = resolve(__dirname, "..", "public");

const svg = await readFile(resolve(publicDir, "favicon.svg"), "utf8");

const targets = [
  { size: 16, file: "favicon-16x16.png" },
  { size: 32, file: "favicon-32x32.png" },
  { size: 180, file: "apple-touch-icon.png" },
  { size: 192, file: "icon-192.png" },
  { size: 512, file: "icon-512.png" },
  { size: 512, file: "icon-512-maskable.png" },
];

for (const { size, file } of targets) {
  const resvg = new Resvg(svg, {
    fitTo: { mode: "width", value: size },
    background: "rgba(0, 0, 0, 0)",
  });
  const png = resvg.render().asPng();
  await writeFile(resolve(publicDir, file), png);
  console.log(`✓ ${file} (${size}×${size}, ${png.length} bytes)`);
}
